# Generated by Django 3.1 on 2020-09-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='watering date')),
                ('fertilizer', models.CharField(choices=[('W', 'Just Water'), ('O', 'Water with Orchid Pro'), ('M', 'Water with Mag Pro Bloombooster'), ('C', 'Water with CalMag')], default='W', max_length=1)),
                ('orchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orchid')),
            ],
        ),
    ]
