# Generated by Django 3.1 on 2020-09-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchid',
            name='supplies',
            field=models.ManyToManyField(to='main_app.Supply'),
        ),
    ]
